apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-gateway
spec:
  rules:
  - host: global.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
